const projects = [
  {
    "id": "commercial-001",
    "number": "001",
    "title": "Food to Power — Headquarters",
    "subtitle": "A multipurpose headquarters building for a food access nonprofit",
    "category": "commercial",
    "year": "2021",
    "location": "Colorado Springs, CO",
    "area": "+/- 3,000 SF",
    "client": "Food to Power Nonprofit",
    "status": "Completed",
    "materials": "Steel Building, Insulated Metal Panels, Aluminum Storefront",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "desc1": "The program of the FTP building includes offices, conference space, a demonstration kitchen, and a large, multipurpose space capable of light distribution, events, and community interface.",
    "desc2": "The structural system is a play on the standard Steel Building, with recessed endcaps covered in wood, and insulated metal panels to give it a clean exterior aesthetic and straightforward envelope.",
    "statement": "A building that works as hard as the organization it serves — simple, honest, and built for the community.",
    "imgs": [
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-01.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-02.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-03.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-04.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-05.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-06.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-07.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-08.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-09.jpg",
      "images/projects/food-to-power-headquarters/food-to-power-headquarters-10.jpg"
    ]
  },
  {
    "id": "commercial-002",
    "number": "002",
    "title": "Yey Salon",
    "subtitle": "Cold shell commercial with beauty salon tenant TI",
    "category": "commercial",
    "year": "2026",
    "location": "Santa Fe, NM",
    "area": "+/- 6,000 SF + 2,000 SF Salon",
    "client": "—",
    "status": "Under Construction",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/yey-salon/yey-salon-02.jpg",
      "images/projects/yey-salon/yey-salon-01.jpg",
      "images/projects/yey-salon/yey-salon-03.jpg",
      "images/projects/yey-salon/yey-salon-04.jpg",
      "images/projects/yey-salon/yey-salon-05.jpg",
      "images/projects/yey-salon/yey-salon-06.jpg",
      "images/projects/yey-salon/yey-salon-07.jpg",
      "images/projects/yey-salon/yey-salon-08.jpg"
    ],
    "materials": "Wood Frame & Trusses, TPO Roof, Aluminum Storefront, Stucco",
    "desc1": "coming soon…",
    "desc2": "",
    "statement": ""
  },
  {
    "id": "commercial-003",
    "number": "003",
    "title": "Lodge Window System",
    "subtitle": "Organic wooden curtain wall window system",
    "category": "commercial",
    "year": "2022",
    "location": "Colorado",
    "area": "Enclosing +/- 9,000 SF",
    "client": "-",
    "status": "Completed",
    "materials": "Micro-lam wood mullions, Insulated metal glazing units, Parametric layout",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "desc1": "An organic wooden curtain wall window system. Conceptualized using parametric design to imitate the natural patterns of Colorado's trees and landscapes. Modeled using Grasshopper & Dynamo scripts in Revit.",
    "desc2": "Project Architect: OZ Architecture (Denver, CO). Window builders: Grabill Windows.",
    "imgs": [
      "images/projects/lodge-window/lodge-window-01.jpg",
      "images/projects/lodge-window/lodge-window-02.jpg",
      "images/projects/lodge-window/lodge-window-03.jpg",
      "images/projects/lodge-window/lodge-window-04.jpg",
      "images/projects/lodge-window/lodge-window-05.jpg",
      "images/projects/lodge-window/lodge-window-06.jpg",
      "images/projects/lodge-window/lodge-window-07.jpg",
      "images/projects/lodge-window/lodge-window-08.jpg",
      "images/projects/lodge-window/lodge-window-09.jpg",
      "images/projects/lodge-window/lodge-window-10.jpg"
    ]
  },
  {
    "id": "commercial-004",
    "number": "004",
    "title": "Coastal Cabins & Kitchen",
    "subtitle": "—",
    "category": "commercial",
    "year": "2026",
    "location": "—",
    "area": "—",
    "client": "—",
    "status": "—",
    "materials": "—",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "desc1": "—",
    "desc2": "",
    "imgs": [
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-11.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-01.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-02.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-03.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-04.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-05.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-06.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-07.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-08.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-09.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-10.jpg",
      "images/projects/coastal-cabins-kitchen/coastal-cabins-kitchen-12.jpg"
    ]
  },
  {
    "id": "residential-001",
    "number": "001",
    "title": "Jewel Box",
    "subtitle": "Santa Fe style contemporary residence design for use at Tierra Antigua",
    "category": "residential",
    "year": "2026",
    "location": "Tierra Antigua Subdivision, Santa Fe, NM",
    "area": "+/- 2,750 SF",
    "client": "Arete Homes of Santa Fe",
    "status": "Under Construction",
    "materials": "Wood Frame & Trusses, Clad Wood Windows",
    "colors": [
      "ph-d",
      "ph-e",
      "ph-f"
    ],
    "desc1": "The Jewel Box design offers a contemporary take on some of our favorite \\\"Santa Fe Style\\\" expressions. The plan is designed to deliver maximum interaction with the outdoors, whilst also proving to be an intuitive, easy to use floorplan for the user.",
    "desc2": "The design draws from traditional adobe massing — flat roofs, deep overhangs, and thick-wall openings — while introducing a contemporary material palette of smooth stucco, dark steel framing, and warm wood soffits. The result is a home that feels rooted in the landscape but unmistakably of its time.",
    "statement": "We wanted every room to reach toward the sky. Santa Fe gives you that light — we just tried not to get in the way.",
    "imgs": [
      "images/projects/jewel-box/jewel-box-01.jpg",
      "images/projects/jewel-box/jewel-box-02.jpg",
      "images/projects/jewel-box/jewel-box-03.jpg",
      "images/projects/jewel-box/jewel-box-04.jpg"
    ]
  },
  {
    "id": "residential-002",
    "number": "002",
    "title": "Orchard Casita",
    "subtitle": "Farmhouse casita build with AAC block",
    "category": "residential",
    "year": "2023",
    "location": "Villanueva, NM",
    "area": "+/- 800 SF + Loft",
    "client": "Gundrey Family",
    "status": "Complete",
    "materials": "Autoclaved Aerated Concrete (AAC), Standing Seam Metal Roof, Clad Wood Windows",
    "colors": [
      "ph-d",
      "ph-e",
      "ph-f"
    ],
    "desc1": "The Orchard Casita is a compact little house that sits at the edge of a flourishing apple orchard. The walls are made of 12\" AAC, a magnificent material well known in other regions of the world - unfortunately rarely known in the US.",
    "desc2": "",
    "statement": "",
    "imgs": [
      "images/projects/orchard-casita/orchard-casita-01.jpg",
      "images/projects/orchard-casita/orchard-casita-02.jpg",
      "images/projects/orchard-casita/orchard-casita-03.jpg",
      "images/projects/orchard-casita/orchard-casita-04.jpg",
      "images/projects/orchard-casita/orchard-casita-05.jpg",
      "images/projects/orchard-casita/orchard-casita-06.jpg",
      "images/projects/orchard-casita/orchard-casita-07.jpg",
      "images/projects/orchard-casita/orchard-casita-08.jpg",
      "images/projects/orchard-casita/orchard-casita-09.jpg"
    ]
  },
  {
    "id": "residential-003",
    "number": "003",
    "title": "Mountain Casita",
    "subtitle": "Whimsical small ADU dwelling nestled into the hill and forest",
    "category": "residential",
    "year": "2026",
    "location": "Santa Fe, NM",
    "area": "+/- 1,250 SF heated",
    "client": "—",
    "status": "In Permit",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/mountain-casita/mountain-casita-01.png",
      "images/projects/mountain-casita/mountain-casita-02.png",
      "images/projects/mountain-casita/mountain-casita-03.png"
    ],
    "materials": "Panelized Prefab Steel Stud System",
    "desc1": "This casita is an exercise in completely moldproof and fire-resistant construction, based on an innovative panelized prefab steel stud system.",
    "desc2": "",
    "statement": ""
  },
  {
    "id": "creative-001",
    "number": "001",
    "title": "Odd Facades",
    "subtitle": "An exploration of eccentricity, ornament, and the limits of architectural form",
    "category": "creative",
    "year": "2024",
    "location": "studio|BOSE",
    "area": "—",
    "client": "—",
    "status": "Research",
    "type": "—",
    "concepts": "—",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/odd-facades/odd-facades-01.jpg",
      "images/projects/odd-facades/odd-facades-02.jpg",
      "images/projects/odd-facades/odd-facades-03.png",
      "images/technology/technology-digital-fabrication-2.jpg",
      "images/projects/odd-facades/odd-facades-05.jpg",
      "images/projects/odd-facades/odd-facades-06.jpg"
    ],
    "materials": "",
    "desc1": "A collection of formally experimental facades — from Victorian wireframe studies to parametric connector plates. Each image is an artifact of a different design inquiry, united by a fascination with surface, structure, and the unexpected.",
    "desc2": ""
  },
  {
    "id": "creative-002",
    "number": "002",
    "title": "AI-Powered Mood Boards",
    "subtitle": "Material palettes designed by us and rendered through our proprietary image-making application, based on Gemini",
    "category": "creative",
    "year": "2025",
    "location": "studio|BOSE",
    "area": "—",
    "client": "—",
    "status": "Ongoing",
    "type": "—",
    "concepts": "—",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-01.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-02.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-03.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-04.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-05.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-06.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-07.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-08.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-09.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-10.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-11.png",
      "images/projects/ai-powered-mood-boards/ai-powered-mood-boards-12.png"
    ],
    "materials": "",
    "desc1": "We use AI-generated imagery as a rapid design tool — composing material palettes, testing color relationships, and exploring spatial moods before a single physical sample is ordered.",
    "desc2": ""
  },
  {
    "id": "residential-004",
    "number": "004",
    "title": "Lorenzo Lane Redux",
    "subtitle": "Complete overhaul of a decaying Santa Fe home in the historic districts",
    "category": "residential",
    "year": "2024",
    "location": "Lorenzo Ln, Santa Fe, NM",
    "area": "+/- 1,950 SF",
    "client": "Self Developed",
    "status": "Complete",
    "materials": "Adobe, 2x6, TPO Roof, Stucco, Clad Wood Windows",
    "colors": [
      "ph-d",
      "ph-e",
      "ph-f"
    ],
    "desc1": "Situated in the Eastside & Downtown Historic district of Santa Fe, the Lorenzo house needed more than just a little love. While much of the building was restructured, the original orientation, fenestration, single plate height, proportions, and way of life on the site were honored and reinforced.",
    "desc2": "The landscape is a naturalistic approach with native grasses, evergreen screening, and colorful draught-resistant plantings.",
    "statement": "",
    "imgs": [
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-01.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-02.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-03.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-04.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-05.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-06.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-07.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-08.png",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-09.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-10.jpg",
      "images/projects/lorenzo-lane-redux/lorenzo-lane-redux-11.jpg"
    ]
  },
  {
    "id": "creative-003",
    "number": "003",
    "title": "Burning Man Dinosaur Head",
    "subtitle": "A geodesic steel-frame dinosaur head installation designed for the playa",
    "category": "creative",
    "year": "2017",
    "location": "Black Rock City, NV",
    "area": "—",
    "client": "—",
    "status": "Complete",
    "type": "Temporary occupiable dinosaur head structure",
    "concepts": "Geodesic form, triangulated bracing, individual panels",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-01.jpg",
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-02.jpg",
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-03.png",
      "images/technology/technology-rhino-parametrics.jpg",
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-05.png",
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-06.png",
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-07.jpg",
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-08.jpg",
      "images/projects/burning-man-dinosaur-head/burning-man-dinosaur-head-09.jpg"
    ],
    "materials": "",
    "desc1": "",
    "desc2": ""
  },
  {
    "id": "creative-004",
    "number": "004",
    "title": "Treehouse Module",
    "subtitle": "A self-sufficient modular treehouse system designed for off-grid living",
    "category": "creative",
    "year": "2020",
    "location": "studio|BOSE",
    "area": "—",
    "client": "—",
    "status": "Research",
    "type": "Competition",
    "concepts": "Single lodging unit that exists amongst the tree canopies of the forest",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/treehouse-module/treehouse-module-01.jpg",
      "images/projects/treehouse-module/treehouse-module-02.jpg",
      "images/projects/treehouse-module/treehouse-module-03.jpg",
      "images/projects/treehouse-module/treehouse-module-04.jpg",
      "images/projects/treehouse-module/treehouse-module-05.jpg",
      "images/projects/treehouse-module/treehouse-module-06.png"
    ],
    "materials": "",
    "desc1": "",
    "desc2": ""
  },
  {
    "id": "creative-005",
    "number": "005",
    "title": "Santa.F.Ai Concept Designs",
    "subtitle": "Concept imagery work imagining the future of the Santa Fe style",
    "category": "creative",
    "year": "2025",
    "location": "studio|BOSE",
    "area": "—",
    "client": "—",
    "status": "Ongoing",
    "type": "Conceptual",
    "concepts": "Future forms, materials, density, evolution",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-01.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-02.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-03.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-04.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-05.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-06.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-07.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-08.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-09.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-10.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-11.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-12.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-13.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-14.jpg",
      "images/projects/santa-fai-concept-designs/santa-fai-concept-designs-15.jpg"
    ],
    "materials": "",
    "desc1": "What does Santa Fe look like in fifty years? These images are an attempt to ask that question visually — using AI as a design tool to push the adobe tradition into new territory: denser, taller, stranger, and still rooted in the land.",
    "desc2": ""
  },
  {
    "id": "creative-006",
    "number": "006",
    "title": "Wild & Domestic",
    "subtitle": "Cliff Swallow inspired dwelling units & masonry units",
    "category": "creative",
    "year": "2018",
    "location": "-",
    "area": "—",
    "client": "—",
    "status": "Unbuilt",
    "type": "Research, Conceptual",
    "concepts": "Digital Fabrication, Ceramic Printing, Modular Living, Biomimmicry, Earthen Material",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/wild-domestic/wild-domestic-01.jpg",
      "images/projects/wild-domestic/wild-domestic-02.jpg",
      "images/projects/wild-domestic/wild-domestic-03.jpg",
      "images/projects/wild-domestic/wild-domestic-04.jpg",
      "images/projects/wild-domestic/wild-domestic-05.jpg",
      "images/projects/wild-domestic/wild-domestic-06.jpg",
      "images/projects/wild-domestic/wild-domestic-07.jpg",
      "images/projects/wild-domestic/wild-domestic-08.jpg",
      "images/projects/wild-domestic/wild-domestic-09.jpg",
      "images/projects/wild-domestic/wild-domestic-10.jpg",
      "images/projects/wild-domestic/wild-domestic-11.jpg",
      "images/projects/wild-domestic/wild-domestic-12.jpg",
      "images/projects/wild-domestic/wild-domestic-13.jpg",
      "images/projects/wild-domestic/wild-domestic-14.jpg",
      "images/projects/wild-domestic/wild-domestic-15.jpg",
      "images/projects/wild-domestic/wild-domestic-16.jpg",
      "images/projects/wild-domestic/wild-domestic-17.jpg",
      "images/projects/wild-domestic/wild-domestic-18.jpg",
      "images/projects/wild-domestic/wild-domestic-19.jpg",
      "images/projects/wild-domestic/wild-domestic-20.jpg",
      "images/projects/wild-domestic/wild-domestic-21.jpg",
      "images/projects/wild-domestic/wild-domestic-22.jpg",
      "images/projects/wild-domestic/wild-domestic-23.jpg",
      "images/projects/wild-domestic/wild-domestic-24.jpg",
      "images/projects/wild-domestic/wild-domestic-25.jpg",
      "images/projects/wild-domestic/wild-domestic-26.jpg",
      "images/projects/wild-domestic/wild-domestic-27.jpg",
      "images/projects/wild-domestic/wild-domestic-28.jpg",
      "images/projects/wild-domestic/wild-domestic-29.jpg",
      "images/projects/wild-domestic/wild-domestic-30.jpg",
      "images/projects/wild-domestic/wild-domestic-31.jpg"
    ],
    "materials": "-",
    "desc1": "",
    "desc2": ""
  },
  {
    "id": "creative-007",
    "number": "007",
    "title": "Topanga House Model",
    "subtitle": "Architectural model of a built work (by others) in Topanga, CA.",
    "category": "creative",
    "year": "2014",
    "location": "Topanga, CA",
    "area": "—",
    "client": "—",
    "status": "Built",
    "type": "Scale Architectural Model",
    "concepts": "",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/topanga-house-model/topanga-house-model-02.jpg",
      "images/projects/topanga-house-model/topanga-house-model-01.jpg",
      "images/projects/topanga-house-model/topanga-house-model-03.jpg",
      "images/projects/topanga-house-model/topanga-house-model-04.jpg",
      "images/projects/topanga-house-model/topanga-house-model-05.jpg",
      "images/projects/topanga-house-model/topanga-house-model-06.jpg",
      "images/projects/topanga-house-model/topanga-house-model-07.jpg",
      "images/projects/topanga-house-model/topanga-house-model-08.jpg"
    ],
    "materials": "",
    "desc1": "",
    "desc2": ""
  },
  {
    "id": "creative-008",
    "number": "008",
    "title": "By Hand",
    "subtitle": "—",
    "category": "creative",
    "year": "2026",
    "location": "—",
    "area": "—",
    "client": "—",
    "status": "—",
    "type": "—",
    "concepts": "—",
    "colors": [
      "ph-a",
      "ph-b",
      "ph-c"
    ],
    "imgs": [
      "images/projects/by-hand/by-hand-02.jpg",
      "images/projects/by-hand/by-hand-01.jpg",
      "images/projects/by-hand/by-hand-03.jpg",
      "images/projects/by-hand/by-hand-04.jpg",
      "images/projects/by-hand/by-hand-05.jpg",
      "images/projects/by-hand/by-hand-06.jpg",
      "images/projects/by-hand/by-hand-07.jpg",
      "images/projects/by-hand/by-hand-08.jpg",
      "images/projects/by-hand/by-hand-09.jpg",
      "images/projects/by-hand/by-hand-10.jpg",
      "images/projects/by-hand/by-hand-11.jpg",
      "images/projects/by-hand/by-hand-12.jpg",
      "images/projects/by-hand/by-hand-13.jpg",
      "images/projects/by-hand/by-hand-14.jpg",
      "images/projects/by-hand/by-hand-15.jpg",
      "images/projects/by-hand/by-hand-16.jpg"
    ],
    "materials": "Graphite, Pen, Acrylic, Watercolor",
    "desc1": "The more you draw, the more you see. We value the process of sketching as  direct link to the mind that bypasses the cumbersome translation needed to convince software to show what you have in mind. ",
    "desc2": ""
  },
  {
    "id": "residential-005",
    "number": "005",
    "title": "Meadowlark Residence",
    "subtitle": "A heavy timber cathedral ceiling residence oriented towards the wildgrass meadow",
    "category": "residential",
    "year": "2025",
    "location": "Tierra Antigua, Santa Fe",
    "area": "+/- 2500 SF",
    "client": "Arete Homes of Santa Fe",
    "status": "Permitting",
    "materials": "Wood Frame, Heavy Timber, Metal Roof, Stucco, Metal Clad Windows",
    "colors": [
      "ph-d",
      "ph-e",
      "ph-f"
    ],
    "imgs": [
      "images/projects/meadowlark/meadowlark-01.jpg",
      "images/projects/meadowlark/meadowlark-02.jpg",
      "images/projects/meadowlark/meadowlark-03.jpg",
      "images/projects/meadowlark/meadowlark-04.jpg",
      "images/projects/meadowlark/meadowlark-05.jpg",
      "images/projects/meadowlark/meadowlark-06.jpg",
      "images/projects/meadowlark/meadowlark-07.jpg",
      "images/projects/meadowlark/meadowlark-08.jpg",
      "images/projects/meadowlark/meadowlark-09.jpg"
    ],
    "desc1": "",
    "desc2": ""
  }
];